# Based on : https://github.com/boostorg/hana/blob/master/.travis.yml
# Project language
language: c++
# sudo 
sudo: required
# Global variable
env:
  global:
    - DEPS_ROOT=~/deps
    - OPENBLAS_ROOT=$DEPS_ROOT/openblas
    - OPENCV_ROOT=$DEPS_ROOT/opencv
    - DOXYGEN_ROOT=$DEPS_ROOT/doyxgen
    - CMAKE_OPTIONS=-DWITH_EXAMPLES=ON
# Define list of OS and compiler to test on
matrix:
  include:
    # Linux - GCC
    - os: linux
      dist: trusty
      env: NSTRIP=1 CMAKE_URL=https://cmake.org/files/v3.4/cmake-3.4.3-Linux-x86_64.tar.gz
      compiler: gcc
    
    # Linux - Clang
    - os: linux
      dist: trusty
      env: NSTRIP=1 CMAKE_URL=https://cmake.org/files/v3.4/cmake-3.4.3-Linux-x86_64.tar.gz 
      compiler: clang
    
    # OSX - Clang
    - os: osx
      osx_image: xcode8.3
      env: NSTRIP=3 CMAKE_URL=https://cmake.org/files/v3.4/cmake-3.4.3-Darwin-x86_64.tar.gz
      compiler: clang
      
    # Doc Generator
    - os: linux
      dist: trusty
      env: DOCUMENTATION=TRUE NSTRIP=1 DOXYGEN_URL=http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.13.linux.bin.tar.gz CMAKE_OPTIONS="${CMAKE_OPTIONS} -DWITH_DOCS=ON"
      compiler: gcc
# Add packages
addons:
  apt:
    packages:
      # Add libc++ https://github.com/mapbox/mapbox-gl-native/issues/287
      - libc++1
      - libc++-dev
      - gfortran
      # Doxygen
      - graphviz
      - flex
      - bison
      - libiconv-hook*
# Cache dependencies
cache:
  directories:
    - $OPENBLAS_ROOT
    - $OPENCV_ROOT
    - $DOXYGEN_ROOT
    - $HOME/Library/Caches/Homebrew
# Limit cloning depth
git:
  depth: 3
# Install dependencies needed by library
install:
  ############################################################################
  # All the dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
  ############################################################################
  - mkdir -p $DEPS_ROOT && cd $DEPS_ROOT
  
  ############################################################################
  # Install a recent CMake
  ############################################################################
  - |
    mkdir cmake && curl -o cmake.tar.gz -O ${CMAKE_URL} && tar -C cmake/ --strip-components=${NSTRIP} -xzf cmake.tar.gz
    export PATH=$DEPS_ROOT/cmake/bin:${PATH}
  - cmake --version
  
  ############################################################################
  # Install OpenBLAS (only on linux)
  ############################################################################
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      $TRAVIS_BUILD_DIR/travis/install-openblas.sh $OPENBLAS_ROOT
    fi
    
  ############################################################################
  # Install nasm for jpeg-turbo lib
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      sudo apt-get -qq update
      sudo apt-get install -y nasm
    else
      brew upgrade nasm || brew install nasm
    fi
    nasm -v && which nasm
    
  ############################################################################
  # Install OpenCV
  ############################################################################
  - $TRAVIS_BUILD_DIR/travis/install-opencv.sh $OPENCV_ROOT
  
  ############################################################################
  # Install a recent Doxygen
  ############################################################################
  - |
    if [[ "$DOCUMENTATION" == "TRUE" ]]; then
      $TRAVIS_BUILD_DIR/travis/install-doxygen.sh $DOXYGEN_ROOT
      doxygen --version
    fi
  
before_script:
  ############################################################################
  # Set the git identity (for pushing the documentation and the benchmarks)
  ############################################################################
  - git config --global user.name "Travis bot"
  - git config --global user.email "<>"
  
# Compilation scripts start here
script:
  - $TRAVIS_BUILD_DIR/travis/build-library.sh
  # Run UnitTest
  - $TRAVIS_BUILD_DIR/travis/test-library.sh
  # Build docs
  - $TRAVIS_BUILD_DIR/travis/build-doc.sh

# Setup SSH for deployment
before_deploy:
  - |
    cd $TRAVIS_BUILD_DIR
    openssl aes-256-cbc -K $encrypted_59ae97b0ca3d_key -iv $encrypted_59ae97b0ca3d_iv -in travis/.deploy-key.enc -out deploy-key -d
    chmod 600 deploy-key
    eval `ssh-agent -s`
    ssh-add deploy-key
# Push freshly build documentation online
deploy:
  provider: script
  skip_cleanup: true
  script: $TRAVIS_BUILD_DIR/travis/deploy-doc.sh
  on:
    branch: develop
  
# Notifications
notifications:
  slack:
    secure: ItARuy/RFKJEr2VtpPnxaKlrdElHaVfeeVzbWnfjnPrzCcqHc++P/O52DTtGyGuqd3+szNuvVcnAH1vPP5TlbxG/Gxox2fU9Kdwt56Ll5hz6jHqeV2tSuzp6MTE3k35AGStVtXI6RHdlwfO3HkX5c9XAN6dyeOGzfi5YU1it2Easo0hm9aaXVZPBtvIUkU39vzHa0W0ZgZlvO9XsBGScIbMGdLm81gEhPB0J7w/vijisityVlhw50DXoApFLFL5QUAYcBf7ATm/kl36GY2cTAO/KBEdPNBE6Vu0swXwFAX/HYhyzXjPC/VBkFgUG722CO61M4S8M3TylJTtqZantA5hakYuNVNEnhlzmVkBF9qmMrW0PGIcApyZZ4pKZ498PrSU4NYEz+c8VUlyQXxE6QmVTI2hfMk1SbqrpQg+dalbjj0Osp3c+kR1rR4CVYqhTT1JeiKqs+Wz/rWn3J6BHPNIEMv2uVP8XWqpdBXbJEGJLa40x6ylfbr2+WKHBZsOCkzup00EjAMzzQLym0EvdomkIF5F1gJqTbCMkZSWLb0F8zTxqbQZ0Agz9n/XSJraKyBO1TLpYCgsxF5WP8XD1Xw1cDsunidvwTP1xeVvfN9jwxBOQYPBfWI2oqG/u5rHQJ4K7JImuhlfu3d1NZlGX+eNUKghMrCakQTHzKYj9tlA=
  