# Options for building CHLIB.

# Build shared libraries by default.
OPTION(CHLIB_SHARED_LIBS "Build shared libraries." ON)
IF(CHLIB_SHARED_LIBS)
  SET(CHLIB_LIB_PREFIX ${CMAKE_SHARED_LIBRARY_PREFIX})
  SET(CHLIB_LIB_SUFFIX ${CMAKE_SHARED_LIBRARY_SUFFIX})
  SET(CHLIB_LIB_TYPE "SHARED")
#  SET(CMAKE_FIND_LIBRARY_SUFFIXES ${CMAKE_SHARED_LIBRARY_SUFFIX})
  IF(WIN32)
    SET(CMAKE_FIND_LIBRARY_SUFFIXES ${CMAKE_IMPORT_LIBRARY_SUFFIX})
  ENDIF(WIN32)
ELSE(CHLIB_SHARED_LIBS)
  SET(CHLIB_LIB_PREFIX ${CMAKE_STATIC_LIBRARY_PREFIX})
  SET(CHLIB_LIB_SUFFIX ${CMAKE_STATIC_LIBRARY_SUFFIX})
  SET(CHLIB_LIB_TYPE "STATIC")
  SET(CMAKE_FIND_LIBRARY_SUFFIXES ${CMAKE_STATIC_LIBRARY_SUFFIX})
ENDIF(CHLIB_SHARED_LIBS)
mark_as_advanced(CHLIB_SHARED_LIBS)

# Build documentation with doxygen, default off
OPTION(WITH_DOCS "Build doxygen documentation" OFF)

# Build examples
OPTION(WITH_EXAMPLES "Build examples executable" OFF)

# Build unit test
OPTION(WITH_TESTS "Build unit test targets" ON)