set(CHLIB_SUBSYSTEMS_MODULES ${CHLIB_SUBSYSTEMS})

set(CHLIBCONFIG_AVAILABLE_COMPONENTS)
set(CHLIBCONFIG_AVAILABLE_COMPONENTS_LIST)
set(CHLIBCONFIG_INTERNAL_DEPENDENCIES)
foreach(_ss ${CHLIB_SUBSYSTEMS_MODULES})
  CHLIB_GET_SUBSYS_STATUS(_status ${_ss})
  if(_status)
    set(CHLIBCONFIG_AVAILABLE_COMPONENTS "${CHLIBCONFIG_AVAILABLE_COMPONENTS} ${_ss}")
    set(CHLIBCONFIG_AVAILABLE_COMPONENTS_LIST "${CHLIBCONFIG_AVAILABLE_COMPONENTS_LIST}\n# - ${_ss}")
    GET_IN_MAP(_deps CHLIB_SUBSYS_DEPS ${_ss})
    if(_deps)
        set(CHLIBCONFIG_INTERNAL_DEPENDENCIES "${CHLIBCONFIG_INTERNAL_DEPENDENCIES}set(chlib_${_ss}_int_dep ")
        foreach(_dep ${_deps})
            set(CHLIBCONFIG_INTERNAL_DEPENDENCIES "${CHLIBCONFIG_INTERNAL_DEPENDENCIES}${_dep} ")
        endforeach(_dep)
        set(CHLIBCONFIG_INTERNAL_DEPENDENCIES "${CHLIBCONFIG_INTERNAL_DEPENDENCIES})\n")
    endif(_deps)
    #look for subsystems
    string(TOUPPER "CHLIB_${_ss}_SUBSYS" CHLIB_SUBSYS_SUBSYS)
    if (${CHLIB_SUBSYS_SUBSYS})
      string(TOUPPER "CHLIB_${_ss}_SUBSYS_STATUS" CHLIB_SUBSYS_SUBSYS_STATUS)
      foreach(_sub ${${CHLIB_SUBSYS_SUBSYS}})
        CHLIB_GET_SUBSUBSYS_STATUS(_sub_status ${_ss} ${_sub})
        if (_sub_status)
          set(CHLIBCONFIG_AVAILABLE_COMPONENTS "${CHLIBCONFIG_AVAILABLE_COMPONENTS} ${_sub}")
          set(CHLIBCONFIG_AVAILABLE_COMPONENTS_LIST "${CHLIBCONFIG_AVAILABLE_COMPONENTS_LIST}\n# - ${_sub}")
          GET_IN_MAP(_deps CHLIB_SUBSYS_DEPS ${_ss}_${sub})
          if(_deps)
            set(CHLIBCONFIG_INTERNAL_DEPENDENCIES "${CHLIBCONFIG_INTERNAL_DEPENDENCIES}set(chlib_${_sub}_int_dep ")
            foreach(_dep ${_deps})
              set(CHLIBCONFIG_INTERNAL_DEPENDENCIES "${CHLIBCONFIG_INTERNAL_DEPENDENCIES}${_dep} ")
            endforeach(_dep)
            set(CHLIBCONFIG_INTERNAL_DEPENDENCIES "${CHLIBCONFIG_INTERNAL_DEPENDENCIES})\n")
          endif(_deps)
        endif(_sub_status)
      endforeach(_sub)
    endif (${CHLIB_SUBSYS_SUBSYS})
  endif(_status)
endforeach(_ss)

configure_file("${CHLIB_SOURCE_DIR}/cmake/CHLIBConfig.cmake.in"
               "${CHLIB_BINARY_DIR}/CHLIBConfig.cmake" @ONLY)
configure_file("${CHLIB_SOURCE_DIR}/cmake/CHLIBConfigVersion.cmake.in"
               "${CHLIB_BINARY_DIR}/CHLIBConfigVersion.cmake" @ONLY)
install(FILES
        "${CHLIB_BINARY_DIR}/CHLIBConfig.cmake"
        "${CHLIB_BINARY_DIR}/CHLIBConfigVersion.cmake"
        COMPONENT chlibconfig
        DESTINATION ${CHLIBCONFIG_INSTALL_DIR})